
image: registry.asimov.cfms.org.uk/wp2/libspmv/base:latest

build:
  stage: build
  script:
    - cmake . -DCMAKE_PREFIX_PATH=/usr/local && make -j && make install
    - export OMP_NUM_THREADS=1
    - ./demos/matvecmain
    - mpirun -n 2 ./demos/matvecmain
